output_dir: translations/bert_large_pt_cased_trained_in/assin1
do_cross_tests: 1
datasets:
    assin:
        do_cross_tests: 1
        do_label_translation : 0
        by_class_metric: 1
        subsets:
            - full         
        data_args:
            dataset_name: assin
            rename_columns:
                entailment_judgment: label
            label_names:
                predict_dataset:
                    0: NONE
                    1: ENTAILMENT
                    2: PARAPHRASE
                    3: CONTRADICTION 
                    4: NEUTRAL  
    assin2:
        do_cross_tests: 1
        do_label_translation : 1
        by_class_metric: 1
        data_args:
            dataset_name: assin2
            rename_columns:
                entailment_judgment: label
            label_names:
                predict_dataset:
                    0: NONE
                    1: ENTAILMENT
                    2: PARAPHRASE
                    3: CONTRADICTION
                    4: NEUTRAL

    dlb/plue:
        do_cross_tests: 1
        do_label_translation : 1
        by_class_metric: 1
        subsets:
            - mnli        
        data_args:
            dataset_name: plue            
            label_names:
                predict_dataset:
                    0: entailment
                    1: neutral
                    2: contradiction
            test_dataset_split: validation_matched
            label_map:
                entailment: 1
                neutral: 0
                contradiction: 2
            new_label_map:
                0: NONE
                1: ENTAILMENT
                2: CONTRADICTION