defaults:
  - model: bert_large_pt_cased
  - data_training: no_max_train_predict_samples
  - hyperparameter_tuning: bert_large_pt_cased
  - training: bert_large_pt_cased
  - cross_tests: cross_tests
  - _self_