model_name_or_path: xlm-roberta-base
tokenizer_name: XLMRobertaTokenizer
download_fine_tuned: 1
fine_tuned_model_local_dir: "XLM-Roberta_fine_tuned"
fine_tuned_wandb_name_tag: gio_projs/XLM-Roberta/model:v12