output_dir: training_checkpoints/assin_xlmr
overwrite_output_dir: 1
do_train: 1
do_eval: 1
do_predict: 1
evaluation_strategy: steps
report_to: wandb
eval_steps: 100
save_strategy: steps
logging_strategy: epoch
load_best_model_at_end: 1
remove_unused_columns: 1
fp16: 1