do_hyperparameter_tuning: 0
load_optimized_parameters: 0
optimized_metric: eval/accuracy
training_args:
    output_dir: vit-sweeps,
    report_to: wandb
    save_strategy: epoch
    evaluation_strategy: epoch
    logging_strategy: epoch
    load_best_model_at_end: 1
    remove_unused_columns: 0
    fp16: 1
project_name: xlm_roberta_best
sweep_id: 24qrauja
sweep_config:
    method: grid
    parameters:
        epochs:
            values: 
                - 1
                - 2 
                - 3
        batch_size:
            values:
                - 8
                - 16
                - 32
                - 64
        weight_decay:
            values:
                - 0.0
                - 0.1
                - 0.2
                - 0.3
                - 0.4
                - 0.5
