do_hyperparameter_tuning: 1
optimized_metric: eval/accuracy
project_path: gio_projs/plue_mnli_bert_large_pt_cased_v1
sweep_id: ""
sweep_config:
    metric:
        name: loss
        goal: minimize
    method: grid
    parameters:
        num_train_epochs:
            values: 
                - 2 
                - 3
                - 4
        per_device_train_batch_size:
            values:
                - 16
                - 32
        learning_rate:
            values:
              - 0.00005
              - 0.00003
              - 0.00002

