model_name_or_path: xlm-roberta-base
tokenizer_name: XLMRobertaTokenizer
download_fine_tuned: 0
fine_tuned_model_local_dir: models/XLM-Roberta_assin
fine_tuned_wandb_name_tag: gio_projs/XLM-Roberta/model:v12