do_hyperparameter_tuning: 0
optimized_metric: eval/accuracy
project_path: gio_projs/assin-XLM-Roberta_v2
sweep_id: ""
sweep_config:
    metric:
        name: loss
        goal: minimize
    method: grid
    parameters:
        epochs:
            values: 
                - 1
                - 2 
                - 3
        batch_size:
            values:
                - 8
                - 16
                - 32
                - 64
        weight_decay:
            values:
                - 0.0
                - 0.1
                - 0.2
                - 0.3
                - 0.4
                - 0.5
